### PR TITLE
added login & sign in

### PR DESCRIPTION
**Pull request by DHRUVA-N-L-CHOUDHARY**
@sijin-raj  I have added the login page and signup page with the firebase email auth link to your firebase account and have a check on the fixed bug.

### CODE REVIEW

**Comment by sijin-raj** [comment]
Thank you for your contribution in our project 🎉.. Happy Hacking

**Comment by DHRUVA-N-L-CHOUDHARY** [comment]
Please have a look over my PR.

**Comment by sijin-raj** [comment]
Please add the screenshot of login and signup screen

**Comment by DHRUVA-N-L-CHOUDHARY** [comment]
image
image
image
image

**Comment by DHRUVA-N-L-CHOUDHARY** [comment]
@sijin-raj  I have updated the screenshots required and code must be able to run now.

**Review by sijin-raj — APPROVED** [review]
Thanks for your Contribution . Happy Hacking

**Pull request merged**
